---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.9.10
            forwarded_port:
                GyOqcCVraoHs:
                    host: '8080'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                manifest_file: default.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            X6YKgxcN13BD:
                source: ./www
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - build-essential
        - vim
        - curl
        - git-core
        - php-console-table
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
        - vhost_alias
    vhosts:
        VybTxSjcyuiX:
            servername: drupal8.dev
            serveraliases:
                - www.drupal8.dev
            docroot: /var/www/drupal8.dev
            port: '80'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
php:
    install: '1'
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - gd
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - APC
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: America/Mexico_City
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: '1'
    settings:
        drush.tag_branch: master
mysql:
    install: '1'
    root_password: drupal
    phpmyadmin: 0
    adminer: 0
    databases:
        JqSYSoWh2ONg:
            grant:
                - ALL
            name: drupal
            host: localhost
            user: drupal
            password: drupal
            sql_file: ''
postgresql:
    install: '1'
    settings:
        root_password: drupal
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases:
        0n9Kksev5pUx:
            grant: ALL
            name: drupal
            user: drupal
            password: drupal
            sql_file: ''
    adminer: 0
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
